services:
  frontend:
    build:
      context: .
      dockerfile: workspace/frontend/Dockerfile.dev
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    depends_on:
      - backend
    networks:
      template-ts-react-fastify-shared:
    volumes:
      - ./workspace/frontend:/app/workspace/frontend
      - ./workspace/shared:/app/workspace/shared
      - ./package.json:/app/package.json
      - /app/node_modules
      - /app/workspace/frontend/node_modules

    environment:
      - ENV_MODE=${ENV_MODE:-development}

  backend:
    build:
      context: .
      dockerfile: workspace/backend/Dockerfile.dev
      args:
        - DOCKERIGNORE_FILE=.dockerignore.dev
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    networks:
      template-ts-react-fastify-shared:

    volumes:
      - ./workspace/backend:/app/workspace/backend
      - ./workspace/shared:/app/workspace/shared
      - ./package.json:/app/package.json
      - /app/node_modules
      - /app/workspace/backend/node_modules
    environment:
      - APP_PORT=${BACKEND_CONTAINER_PORT}


  nginx:
    image: nginx:1.29.3
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      template-ts-react-fastify-shared:

    environment:
      - ENV_MODE=${ENV_MODE:-development}

networks:
  template-ts-react-fastify-shared:
    driver: bridge
